# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' LogLikeliHood_FULL
#'
#' \code{LogLikeliHood_FULL} is a fast \code{C++} implementation that returns a numeric scalar \code{c(0)} with the log-likelihood of the
#' Expectation-Maximization Maximum-Likelihood (EM-ML) algorithm given observations for the explanatory variables governing direct
#' effects on the dependent variable, and observations for explanatory variables that govern the regime
#' transition process. It also returns various diagnostic statistics such as each individual observation's log-likelihood
#' contribution. If parameter 'printLogLike' = 1, the sum of the individual observation's log-likelihood contributions
#' is printed to the console. This fast \code{C++} implementation is several thousand times fast to the \R analog.
#' @export
LogLikeliHood_FULL <- function(param, datax, n_explanatory, n_transition, prob_initial_state_0, printLogLike) {
    .Call(`_TVTP_LogLikeliHood_FULL`, param, datax, n_explanatory, n_transition, prob_initial_state_0, printLogLike)
}

#' LogLikeliHood
#'
#' \code{LogLikeliHood} is a convenience wrapper for function 'LogLikeliHood_FULL' that returns a single numeric scalar
#' with the log-likelihood of the Expectation-Maximization Maximum-Likelihood (EM-ML) algorithm as this is required by some
#' optimizers. This is a fast C++ implementation.
#' @export
LogLikeliHood <- function(param, datax, n_explanatory, n_transition, prob_initial_state_0, printLogLike) {
    .Call(`_TVTP_LogLikeliHood`, param, datax, n_explanatory, n_transition, prob_initial_state_0, printLogLike)
}

#' LogLikeliHood_byObs
#'
#' \code{LogLikeliHood_byObs} is a convenience wrapper for function 'LogLikeliHood_FULL' that returns all observations'
#' log-likelihood constributions as required by certain optimizers.
#' @export
LogLikeliHood_byObs <- function(param, datax, n_explanatory, n_transition, prob_initial_state_0, printLogLike) {
    .Call(`_TVTP_LogLikeliHood_byObs`, param, datax, n_explanatory, n_transition, prob_initial_state_0, printLogLike)
}

#' LogLikeliHood_min
#'
#' \code{LogLikeliHood_min} is a convenience wrapper for function 'LogLikeliHood_FULL' that returns -1 * resulting log-likelihood
#' value as required by certain optimizers
#' @export
LogLikeliHood_min <- function(param, datax, n_explanatory, n_transition, prob_initial_state_0, printLogLike) {
    .Call(`_TVTP_LogLikeliHood_min`, param, datax, n_explanatory, n_transition, prob_initial_state_0, printLogLike)
}

#' LogLikeliHood_RunTimeCheck
#'
#' \code{LogLikeliHood_RunTimeCheck} is a convenience wrapper for function 'LogLikeliHood_FULL' that accepts the number of repetitive log-likelihood
#' calculations as an additional input. This is used to test the systems's computational speed.
#' value as required by certain optimizers
#' @export
LogLikeliHood_RunTimeCheck <- function(param, datax, n_explanatory, n_transition, prob_initial_state_0, printLogLike, n_it) {
    .Call(`_TVTP_LogLikeliHood_RunTimeCheck`, param, datax, n_explanatory, n_transition, prob_initial_state_0, printLogLike, n_it)
}

#' ReturnTiny
#'
#' \code{ReturnTiny} returns the smallest floating number that R can interpret on a regular machine.
#' @export
ReturnTiny <- function() {
    .Call(`_TVTP_ReturnTiny`)
}

